name: effective_dart
description: This package provides the lints according to the Effective Dart guide.
version: 1.0.1
author: Honza Bittner <git@honzabittner.cz>
repository: https://github.com/tenhobi/effective_dart
issue_tracker: https://github.com/tenhobi/effective_dart/issues
homepage: https://github.com/tenhobi/effective_dart

environment:
  sdk: ">=2.0.0 <3.0.0"
